// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhesuwxjrmllftcptlnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoZXN1d3hqcm1sbGZ0Y3B0bG52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2MDQ3MzIsImV4cCI6MjA1NTE4MDczMn0.9CgqkTPvx9RQFyjSvT6Qvea00Tsyx70y3KEutx1gE64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);